version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "build(deps):"
      prefix-development: "build(dev):"

  - package-ecosystem: npm
    directory: /website
    schedule:
      interval: weekly
    commit-message:
      prefix: "build(site):"
